# config
cover: /public/img/codered2.jpg
logo: /public/img/doge.gif
top_saying:
- title: RQE:CC
- content: 代号红皇后：难民营 开发者博客
bottom_saying: 每一个不曾起舞的日子都是对生命的辜负。
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

##############
proc:
  currVer: DEV
  iterVer: 0
  img: /public/img/proc.jpg
  platform: Windows NT
  size: 300M
  proc: 1%
  date: 2016-8-22
###############

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo: duoshuo_name

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Kieran
  link: http://go.kieran.top/
- name: Name
  link: http://domain.com/